### ISSUE TITLE
bug with "yes" button

### ISSUE THREAD

**Issue by Roshanxy** [mattboy9921/SkipNight#10] opened 2020-09-21 15:29 UTC
# Skipnight Configuration
# By Mattboy9921
# https://github.com/mattboy9921/SkipNight
"_mattIsAwesome"=true
# 
# Prevents players from voting if they haven't slept in 3 days.
# Basically, if a player will be attacked by phantoms, they cannot vote.
phantom-support=false
# 
# Enables voting to skip the day.
skipday=false
# 
# Enables voting to skip the night.
skipnight=true

Phantom support is set to false yet I get the message that I need to sleep in a bed first before voting

**Comment by mattboy9921** [comment] 2020-09-21 16:07
I've tested this just now but can't reproduce the issue. Did you restart the server after changing the config?

**Comment by Roshanxy** [comment] 2020-09-21 17:37
yeah and I also get this error

[19:30:05] [Server thread/ERROR]: Could not pass event PlayerBedEnterEvent to SkipNight v1.4.1
java.lang.NullPointerException: null
	at net.mattlabs.skipnight.Vote.voteTypeStringCommand(Vote.java:378) ~[?:?]
	at net.mattlabs.skipnight.Vote.onBedEnter(Vote.java:106) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor45.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.3.jar:git-Paper-202]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.3.jar:git-Paper-202]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.3.jar:git-Paper-202]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.3.jar:git-Paper-202]
	at org.bukkit.craftbukkit.v1_16_R2.event.CraftEventFactory.callPlayerBedEnterEvent(CraftEventFactory.java:279) ~[patched_1.16.3.jar:git-Paper-202]
	at net.minecraft.server.v1_16_R2.EntityPlayer.sleep(EntityPlayer.java:1123) ~[patched_1.16.3.jar:git-Paper-202]
	at net.minecraft.server.v1_16_R2.EntityHuman.sleep(EntityHuman.java:1280) ~[patched_1.16.3.jar:git-Paper-202]
	at net.minecraft.server.v1_16_R2.BlockBed.interact(BlockBed.java:64) ~[patched_1.16.3.jar:git-Paper-202]
	at net.minecraft.server.v1_16_R2.BlockBase$BlockData.interact(BlockBase.java:578) ~[patched_1.16.3.jar:git-Paper-202]
	at net.minecraft.server.v1_16_R2.PlayerInteractManager.a(PlayerInteractManager.java:515) ~[patched_1.16.3.jar:git-Paper-202]
	at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1449) ~[?:git-Paper-202]
	at net.minecraft.server.v1_16_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.16.3.jar:git-Paper-202]
	at net.minecraft.server.v1_16_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.16.3.jar:git-Paper-202]
	at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.3.jar:git-Paper-202]
	at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.3.jar:git-Paper-202]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.3.jar:git-Paper-202]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.3.jar:git-Paper-202]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.3.jar:git-Paper-202]
	at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135) ~[patched_1.16.3.jar:git-Paper-202]
	at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128) ~[patched_1.16.3.jar:git-Paper-202]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.3.jar:git-Paper-202]
	at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:1089) ~[patched_1.16.3.jar:git-Paper-202]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1003) ~[patched_1.16.3.jar:git-Paper-202]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-202]
	at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by mattboy9921** [comment] 2020-09-21 20:03
The NPE has been fixed with 17810f0fe663e4c80f7dfc64d41b13ea4a9e8d83. There was an outdated piece of code from before permissions were separate for day/night. 

Check out [SkipNight 1.4.2](https://github.com/mattboy9921/SkipNight/releases/tag/1.4.2) for the new version with the fix. Let me know if that does it for you and I'll close the issue :)

**Comment by mattboy9921** [comment] 2021-02-22 15:38
Closing this issue as the bug appears to be fixed.

**Closed as completed by mattboy9921** 2021-02-22 15:38 UTC
Labels: bug
